### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#1053]
This is a list of the remaining work on the UI and UX to keep track and aid comms.

## Loading
- [ ] add a loader for the first load of the entire Block @pngwn

## Layout
- [x] Layout: group form input #1054 
- [x] Mobile: Scroll to results #1077

### HighlightedText
- [x] Colors #1119
- [x] Higlight category on legend mouseover #1119
- [x] Show user-provided label (see `demo\diff_texts\run.py`) #1204

### Textbox
- [x] Show placeholder (see `demo\sentiment_analysis\run.py`) #1135
- [x] Textbox size does not adjust to fit the size of the output text (I know this has been brought up in other places), but here is an example (`demo\gpt_j\run.py`) #1153

### JSON
- [x] copy content #1205

### Loading state
- [x] Implement UI #1077
- [x] Loading animation:  https://play.tailwindcss.com/UDwhpFwrmQ?file=css  #1077

### Image
- [x] Sketch has some bugs #1215

### Button
- [x] CSS scoping Vs. component
- [x] Integrate secondary/primary on the Gradio side #1173

### Tabs
- [x] Responsivness

### Forms
- [x] Checkbox/radio focus with tab css

### Carrousel 
- [x] Center image
- [x] Label overflow text

### Table @pngwn
- [x] #962
- [x] #868
- [x] #631
- [x] #945
- [x] #745
- [x] #753
- [x] #1065

### Chart
- [x] Use tailwind colors #1141

## Examples
- [x] Update `DataSet` component #1121

## Typography
- [x] How to implement

## Fonts
- [x] Choose between system and source sans pro
- [x] Performance (loading, too many fonts)

created issue for post 3.0: #1224

## Theming
- [x] #741

**Comment by abidlabs** [comment]
I've noticed some other UI issues as well @pngwn as I've been testing the various demos:

- [ ] `HighlightedText` does not show the `label` (see `demo\sentiment_analysis\run.py`)
- [ ] `Textbox` does not show the `placeholder` (see `demo\sentiment_analysis\run.py`)

**Comment by pngwn** [comment]
I've added these issue to list. The `DataSet` issue will be handled when victor is finished looking at the examples.

I'm going to file a separate issue for the table and add it to the tracking issue for the `DataFrame`.
