### ISSUE TITLE
Dataframe feature requests

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#1201]
The quest for the perfect simple dataframes continues. brain dump so i don't forget. feel free to suggest more nice things.

- [ ] #3286
- [ ] #2667
- [ ] #3284
- [ ] #3283
- [ ] #631 
- [x] Large datasets (pagination or similar)
- [x] #2209
- [x] #2666
- [x] #2006
- [ ] #2020
- [x] Technically a bug #2209 
- [x] #2655
- [x] #2666
- [x] #2688
- [x] #3285
- [x] #2814
- [ ] #2407
- [x] #1178
- [ ] https://github.com/gradio-app/gradio/issues/5230
- [ ] https://github.com/gradio-app/gradio/issues/5054
- [ ] https://github.com/gradio-app/gradio/issues/4981
- [x] https://github.com/gradio-app/gradio/issues/5121

**Comment by Zengyf-CVer** [comment]
@pngwn 

I would like to ask, can the pagination function of `overflow_row_behaviour="paginate"` work normally in `gradio==2.9.4`? I feel like this parameter doesn't seem to work

```
gradio.outputs.Dataframe(self, headers=None, max_rows=20, max_cols=None, overflow_row_behaviour="paginate", type="auto", label=None)
```

**Comment by Zengyf-CVer** [comment]
https://github.com/gradio-app/gradio/issues/1245

**Comment by pngwn** [comment]
@Zengyf-CVer I'd encourage you to try the latest beta, the Dataframe has had many changes although pagination still isn't present. It is a concious omission because we want to get the UX right. Will add this to the above list.

**Comment by Zengyf-CVer** [comment]
@pngwn 
I've tried the last few versions and found that Dataframe's output-side refresh has improved, but pagination really doesn't, which is confusing me.

![ksnip_20220516-094300](https://user-images.githubusercontent.com/41098760/168506172-236e3418-c37f-4bef-8871-5793d89d2354.png)

**Comment by pngwn** [comment]
Pagination has not been implemented yet.

**Comment by abidlabs** [comment]
Going through these issues, I think these are the ones that we should tackle before 4.0:

- [ ] #631  -- logically makes sense since we support adding rows/columns. Has 6 👍
- [ ] #2209 -- we do need to support some sort of pagination, both for UI reasons as well as performance reasons.
- [ ] #2688 or #3285 -- Not sure about priority, but should be pretty straightforward. Has 5 👍
- [ ] #2407 -- comes up frequently, particularly in the context of leaderboards
- [ ] #1178
- [ ] https://github.com/gradio-app/gradio/issues/5054 -- should be straightforward
- [ ] https://github.com/gradio-app/gradio/issues/4981 -- should be straightforward
- [ ] https://github.com/gradio-app/gradio/issues/5121 -- should be straightforward

These are the ones we can do after 4.0 (or delegate to custom components):

- [ ] #3286 and #2667 -- don't see this as a blocker for users
- [ ] #3284 and #3283 -- not really something that has been asked by users
- [ ] #2666 -- less important after pagination is supported 
- [ ] #2006 -- this only makes sense if we merge `gr.Dataframe` and `gr.Dataset`. If we want to do that, this would be the right time, but I personally don't think we should. `gr.Dataset` is designed to view samples -- each row represents one sample, therefore you can click on one entire row. `gr.Dataframe` is designed to let you view/edit 2D mostly numerical data. It feels like the functionality and events are different for the two components, so I'm inclined to keep them separate.
- [ ] #2020 -- quite niche, could be a custom component
- [ ] #2655 -- very niche, they should use css or themes
- [ ] #2814 -- should be custom component
- [ ] https://github.com/gradio-app/gradio/issues/5230 -- feels niche, they can always just reorder in the code to generate the dataframe

**Comment by freddyaboulton** [comment]
I think #2666 and #3286 are orthogonal to pagination. You can have a small (like 20 row) dataframe but the contents are long sentences (like an NLP dataset) and displaying the whole paragraph will overwhelm the page. Have seen it before with the data measurements demo.

Would be good to include in 4.0!

**Comment by abidlabs** [comment]
@freddyaboulton are you suggesting truncating based on the length of the cell's contents? I don't see that as #2666 or #3286 exactly, but perhaps I'm missing something. What solution are you suggesting instead of displaying the whole paragraph?

**Comment by freddyaboulton** [comment]
Sorry I meant that without scroll bars the dataframe could dominate the entire page and push any other components below it outside of the visible area. The same thing happens if you have a not very big number of columns, like ~10, so horizontal scroll bars would help in that case.

**Comment by abidlabs** [comment]
Ok I see -- to address #2666, we could add a `height` parameter to `gr.DataFrame` like we do with the other components that support a variable-sized output (e.g. `Gallery`). This could be a simple alternative to (server-side?) pagination which @pngwn is looking into.

We already support horizontal scrolling, btw, you can test with:

```py
import gradio as gr
import pandas as pd

df = pd.DataFrame([[1, 2, 3, 4, 5, 6, 7, 8, 9]]*10)

gr.Interface(lambda x:df, "textbox", "dataframe").launch()
```

**Comment by pngwn** [comment]
Dataframe is in a good place with only a few feature requests remaining, tackling the current bugs (and maybe a feature) this week but I think this can be closed now and features tackled via the individual issues. We no longer need this tracking issue.

**Comment by arenbeglaryan123** [comment]
I want to select multiple rows in gr.Dafaframe but it's impossible, can anyone help me with that or it doesn't have that functionality?
