### ISSUE TITLE
Test all demos before 3.0 Launch

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#1217]
Hello There;

Testing some/most/all of the demos would be quite a nice QA testing before the launch, any support is honestly welcomed :)
Please mark any of the demos you test, and you can report any issues you have with naming like #1233 and it will be tracked within this issue. 

You could find many gradio examples within demos and get to know about Gradio as well 😄 

The idea is to test them one by one and check there is no problem, you could use the `main` branch. 

**Installation:**
- Latest beta release(easier to install):
```
pip install gradio==3.0b1
```
- [Current dev version](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md#install-gradio-locally-from-the-main-branch)(will contain the latest fixes)

Please check whichever demo you would like to see 😸 

Please let us know in the comments if you can't mark them. We will mark them.

- [x] blocks_flashcard #1233
- [x] blocks_inputs
- [x] blocks_js_methods
- [x] blocks_kinematics
- [x] blocks_layout
- [x] blocks_neural_instrument_coding
- [x] blocks_outputs
- [x] blocks_page_load
- [x] blocks_plug #1237
- [x] blocks_simple_squares
- [x] blocks_speech_text_length
- [x] blocks_static_textbox
- [x] blocks_textarea
- [x] blocks_textbox_max_lines
- [x] blocks_update (related to  #1233)
- [x] blocks_webcam
- [x] blocks_xray
- [x] calculator
- [x] calculator_live
- [x] chatbot
- [x] diff_texts
- [x] digit_classifier #1231
- [x] disease_report #1240 1240
- [x] fake_gan
- [x] fake_gan_2
- [x] fake_gan_no_input
- [x] filter_records
- [x] form_graph
- [x] fraud_detector
- [x] gender_sentence_custom_interpretation
- [x] gender_sentence_default_interpretation
- [x] generate_tone
- [x] gpt_j
- [x] gpt_j_unified
- [x] hello_login
- [x] hello_world
- [x] hello_world_2
- [x] hello_world_3
- [x] image_classifier
- [x] image_classifier_2
- [x] image_classifier_interpretation
- [x] image_mod
- [x] input-output
- [x] kitchen_sink
- [x] longest_word
- [x] main_note
- [x] matrix_transpose
- [x] model3D
- [x] no_input
- [x] outbreak_forecast #1255
- [x] question_answer
- [x] reverse_audio
- [x] sales_projections (bug related to default plot type #1255)
- [x] sentence_builder
- [x] sentiment_analysis
- [x] sepia_filter
- [x] spectogram  (bug related to default plot type #1255)
- [x] sst_or_tts
- [x] stock_forecast
- [x] streaming_stt #1256 1256
- [x] tax_calculator
- [x] text_analysis
- [x] titanic_survival
- [x] video_flip
- [x] webcam
- [x] zip_to_json
- [x] zip_two_files

**Comment by pngwn** [comment]
that's a lot of demos

**Comment by FarukOzderim** [comment]
Note that there is some fixes going on with HighlightedText, so you can pass any demo containing it.

**Comment by pngwn** [comment]
I think we need to merge a couple of PRs in before we do the big final test. We have one or two important ones. We should start on these manual tests when we have released 3.0b to ensure all of the important stuff is done.

**Comment by radames** [comment]
I’ve created a branch and I’ll try to fix as I can the demos https://github.com/gradio-app/gradio/tree/demo-fixes

**Comment by FarukOzderim** [comment]
We had `3.0b0` release out! Everyone please use this release from now on.

**Comment by FarukOzderim** [comment]
Thx to everyone for QAing our demos, I opened the issue to run a maraton on the remaining demos but it is already finished :D
