### ISSUE TITLE
New and Updated Guides for 3.0

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1486]
This is a tracking / brainstorming issues for adding **New Guides** to the [Gradio website](https://www.gradio.app/guides.html), as well as updating older guides to use 3.0 features:

Topics for new guides:
- [ ] Embedding gradio spaces as web components (#703, )
- [ ] Contributing custom components (#1432)
- [ ] Multi-step Blocks (e.g. audio to text to sentiment)
- [ ] Optional components, input-less components, output-less components (#500)
- [ ] Changing visibility
- [ ] Using the 3D model component
- [ ] Plotly (and other plots!) 
- [ ] Building simple games with Gradio
- [ ] Named-entity recognition
- [ ] Real-time webcam
- [ ] Developer mode (reloading, blocks magic) (https://github.com/gradio-app/gradio/issues/1365)
- [ ] other ideas...

Updating older guides:
- [ ] Use web components instead of iframes in guides
- [ ] Generally use 3.x syntax (gradio.components) instead of 2.x syntax (gradio.inputs), etc.
- [ ] Check the real-time speech recognition one

**Comment by abidlabs** [comment]
Let's close this issue and use the doc for tracking. Easier to comment / edit / assign to people. I'll move the guides over
