### ISSUE TITLE
Frontend Testing Tracking Issue

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#4615]
**Tracking Issue for Frontend tests (E2E, Unit tests,  & Visual tests)**

**Goals**
* Have several fully fleshed out E2E tests (using [Playwright](https://playwright.dev/)) that follow how an actual user would use a demo
* Unit tests for every frontend component that tests util functions, internal logic, and the correct passing of props.
* Visual tests using [Chromatic](https://www.chromatic.com/). Helpful for UI and visual regressions.

**TODOs**

_End to End Tests_
Run tests by:
- `pnpm test:browser:full` builds frontend and runs tests
- `pnpm test:browser:verbose` see all errors/warnings
- `pnpm test:browser:debug` opens chromium browser and allows you to step through each line of the test

Use [`kitchen_sink.spec.ts`](https://github.com/gradio-app/gradio/blob/main/js/app/test/kitchen_sink.spec.ts) as reference.
- [x] #4659
- [ ]  `gr.Interface` test (`gr.load()`) maybe for `demo/gpt_j`
- [x] #4746
- [x] streaming use cases
- [x] Event cancelling
- [ ] Making sure filename extensions and names are preserved (model3D can be good for this cause of .obj extension)
- [x] #4687
- [x] #4748
- [ ] Brainstorm more user storyboards for E2E testing

_Unit Tests_
Run tests by:
`pnpm test:run`

Use [`Textbox.test.ts`](https://github.com/gradio-app/gradio/blob/main/js/app/src/components/Textbox/Textbox.test.ts) as reference. List based on most used components
- [x] #4679
- [x] #4711
- [x] #4660
- [x] File - single vs multiple vs directory
- [x] #4701
- [x] Dropdown
- [ ] Checkbox/CheckboxGroup
- [x] #4648
- [x] #4707
- [ ] #4658
- [x] Label

_Visual Testing_
- [ ] dark vs light mode text looks good
- [ ] Loading custom themes looks good
- [ ] blocks_layout demo
- [ ] Gallery styling https://github.com/gradio-app/gradio/pull/4576/files#diff-78d9b29bfe32556861b3814d264f2093e1513af3b943aec92a501a3d2997c7f5
- [ ] Annotated image on small text size https://github.com/gradio-app/gradio/pull/4628

**Comment by pngwn** [comment]
Some testing resources.

Playwright docs are excellent (and extensive). The API docs will be the most helpful as we write tests. The page class in particularly will probably be the mots commonly used.
`Page` API: https://playwright.dev/docs/api/class-page

When you actually get an element that you want to interact with it will return an instance of `Locator` which has lots of useful methods:
`Locator` API: https://playwright.dev/docs/api/class-locator

Playwright also have a nice document about best practices with some examples:
Best Practices: https://playwright.dev/docs/best-practices

They also have other useful guides (check the sidebar and scroll down). Everything i know about playwright is from trial + error and the official docs.

For vitest (untit and integration tests that run in node) we generally use two things.

`@testing-library/svelte` for getting elements and performing interactions and vitest's `expect` module

Testing library DOM functions: https://testing-library.com/docs/queries/about
`expect` API: https://vitest.dev/api/expect.html

Have a look around other parts of these sites too, testing tools like this often have some nice examples and good best practices that can be useful.
