### ISSUE TITLE
4.0 beta tracking + feedback

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#5564]
Place to track all of the bugs, nits, and comments found in the 4.0 branch (`v4`)

# Pre launch
- [x] Get the CI green ✅ 
- [x] python template will replace from PIL import Image with from PIL import <custom-component-name>
- [x] js server launching commands should use full path to executables, e.g. gradio, python, node
- [x] FileExplorer not template_able
- [x] Unpin version before release for docs
- [x] Create simple templates for form components
- [x] Before Release - Set gradio>=4.0,<5.0 in pyproject.toml file for custom components
- [x] https://github.com/gradio-app/gradio/issues/5952
- [x] Add a tag to pyprojecttoml to identify a package as a custom component package
- [x] Front-end dev server will use a port that's used by another app
- [x] Use the data_model in the preprocess
- [x] Model3D component can't be used in dev mode
- [x] Overwrite should clear out the previous directory
- [x] Windows build in CI does not work (frontend)
- [x] Add a server to get backwards compatible type info
- [x] Fix docstrings for events
- [x] Fix website build in v4
- [x] #6223
- [x] ImageMask not working
- [x] ImagePaint not working
- [x] gr.Image(source='upload', tool='color-sketch') not working 
- [x] Tidy up temp file creation in pre/postprocess (particularly Image).
- [x] Empty JSON component looks weird in kitchen_sink_random when cleared ![image](https://github.com/gradio-app/gradio/assets/41651716/2171b46b-faeb-474e-917d-565c7c22b0e4)
- [x] In the external.py module, base64 is being returned as opposed to a temp file for audio/image etc. UI works but caching examples doesn't.
- [x] Interface/Blocks `__call__` method is still calling serialize so it doesn't work
- [x] Have the Fallback component display plain text/number values
- [x] Reduce size of node folder before shipping
- [x] Fix Literal type hint in models
- [x] `gradio_component build` builds the front-end
- [x] Make sure all the dependencies are absolute and not relative in front-end modules
- [x] Layout components can't be templated

# Nice to have
- [x] Create simple templates for Media components
- [x] #6221
- [x] #6220
- [x] #6224
- [x] Emit warning when template directories are overwritten in `gradio cc build` (post launch)
- [x] Write (more) unit tests for gradio_component cli
- [x] Example Css for custom components: https://github.com/gradio-app/gradio/pull/5990/files#r1364407102

# Definitely post launch
- [x] #6222

**Comment by freddyaboulton** [comment]
Thoughts on creating my first custom component:
- [ ] Allow authors to choose the package name. Right now, it defaults to the class name.
- [ ] Rename the front-end template files to match the new component name
- [ ] Use via API page is broken
- [ ] Add node_modules to gitignore

Can we create single-file templates for common components? It's kind of jarring to see so many different files when you're just getting started.

**Comment by abidlabs** [comment]
>  Allow authors to choose the package name. Right now, it defaults to the class name.

If we're referring to the python package, perhaps the default could be `gradio-{component_name}`. This is less likely to already exist on pypi and can make finding gradio-related packages easier

* We should set pydantic version >= 2.0. I was using 1.x and got:

```
ImportError: cannot import name 'RootModel' from 'pydantic' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so)
```

* Running `gradio_component dev` for the first time just froze my terminal. Still trying to figure this one out

**Comment by abidlabs** [comment]
From @aliabid94:

- [ ] also one last thought when I was building out the hostfile component (even though I didn't build it as a custom component) - the css reset made the input checkbox/radio invisible. I had to copy the css from the existing radio component to make it use the theme settings for inputs so they looked the same. I think the reset css should automatically have the input elements. buttons, etc. use the theme css variables instead of stripping away all styling. This way when users create custom components, they will automatically match the theme styling without them having to apply the theme variables

**Comment by duerrsimon** [comment]
Great work so far! 

Few questions here that remain after the demo yesterday: 
-  What's the best way to integrate another CSS framework like tailwind in the build process?  I'd prefer to have multiple components all use the same stylesheet generated by tailwind and not include tailwind multiple times so I guess it would make sense if one could add some global front-end dependencies. I think tailwind supports project set up as monorepos but I am no expert in this.
- Right now looks like all customcomponents will have to be in Svelte, no? Or will it be possible to use e.g React or Vue at a later point as well? 
- Gradio uses @gradio/icons for some icons. Would be great to indicate open icon libraries with similar style so that the iconography stays somewhat consistent

Will be working on a few components now to test stuff more: 
- A modified model3D that will allow input from databases via keyword or via upload, output will be the Svelte wrapper around 3Dmol.js I built to visualize the molecules. 
- I also wanted to build a variant of the dropdown component with cards to provide a bit better explanation of different modes of the app with some rich text and a markdown.  Kind of like this:
![image](https://github.com/gradio-app/gradio/assets/16979577/18192de1-fa49-49da-86eb-e5685c162b0c)

**Comment by abidlabs** [comment]
Thanks @duerrsimon for this feedback!

> What's the best way to integrate another CSS framework like tailwind in the build process? I'd prefer to have multiple components all use the same stylesheet generated by tailwind and not include tailwind multiple times so I guess it would make sense if one could add some global front-end dependencies. I think tailwind supports project set up as monorepos but I am no expert in this.

Tailwind doesn't play well with Gradio themes. I think the better approach would be to use the CSS variables that are also used in the core Gradio components. You can take a look at existing Gradio components to see how to use the CSS variables. Generally, it looks like this: `var(--checkbox-border-color-focus)`. We'll also document these better (cc @hannahblair @pngwn)

> Right now looks like all customcomponents will have to be in Svelte, no? Or will it be possible to use e.g React or Vue at a later point as well?

We'll probably stick to Svelte. Even though I'm primarily backend engineer who tries to stay away from frontend as much as possible, I'll say that the learning curve for Svelte is particularly nice (way easier to pick up than React imo). I've added some resources for learning Svelte to our guide: https://github.com/gradio-app/gradio/wiki/Guide-to-Custom-Components-(Beta)

> Gradio uses @gradio/icons for some icons. Would be great to indicate open icon libraries with similar style so that the iconography stays somewhat consistent

@pngwn do you have any thoughts on this?

**Comment by freddyaboulton** [comment]
Looking forward to the new components @duerrsimon! Thanks for the comments/questions.

**Comment by freddyaboulton** [comment]
https://github.com/gradio-app/gradio/assets/41651716/1fa978e6-ca8e-4574-87e9-cb30d1882a8f
