### ISSUE TITLE
[Tracking] Deprecations related to 5.0

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#8684]
Things to deprecate / remove in 5.0:

- [x]   `concurrency_count` in `queue()`
- [x]  `additional_inputs_accordion_name` in `ChatInterface`
- [x]  `every` in events
- [x]  `thumbnail` in `Interface`
- [x]  `root` in `gr.FileExplorer`
- [x]  `signed_in_value` in `gr.LoginButton`
- [x]  `gr.LogoutButton`

**Comment by abidlabs** [comment]
Many of our constructors have gotten rather large so we should make more args keyword-only args, e.g. in Interface and Examples

**Comment by freddyaboulton** [comment]
- [ ] Integrate ?
- [ ] HFDatasetSaver 🙈

**Comment by abidlabs** [comment]
Yes let's remove `HFDatasetSaver`, we can potentially add a better abstraction in 5.0 (we've heard various proposals from the argilla team) or at least provide a tutorial on how to do this yourself.

**Comment by abidlabs** [comment]
Going to close this for now as all of these are addressed. I anticipate that we might deprecate more things, but we can create new issues for those
