### ISSUE TITLE
[blocks] Test Design

### ISSUE THREAD

**Issue by FarukOzderim** [gradio-app/gradio#894]
**3.0 milestone**
- [x] simple test for blocks config
- [x] drop testing heavily all the library, and just focus on backend functionalities
- [x] make use of fixtures
- [x] move payloads& under a folder
- [ ] make use of async within tests and library

**Low Priority**
- [x] maybe better class&file structuring throughout tests
- [x] When we are launching interfaces, if we can launch server once, update configs of the blocks
- [x] tests should have well defined naming and class structure
- [ ] add examples to docstrings in the codebase
- [ ] docstrings should align with tests
