### ISSUE TITLE
Review components for SSR compatibility

### ISSUE THREAD

**Issue by pngwn** [gradio-app/gradio#9111]
In order to implement #8795 and for general usability of our components as standalone npm packages, we need to ensure that all component are SSR compatible.

**Components**

- [ ] [Accordion](https://www.gradio.app/docs/gradio/accordion)
- [ ] [Column](https://www.gradio.app/docs/gradio/column)
- [ ] [Group](https://www.gradio.app/docs/gradio/group)
- [ ] [Row](https://www.gradio.app/docs/gradio/row)
- [ ] [Tab](https://www.gradio.app/docs/gradio/tab)
- [ ] [AnnotatedImage](https://www.gradio.app/docs/gradio/annotatedimage)
- [ ] [Audio](https://www.gradio.app/docs/gradio/audio)
- [ ] [BarPlot](https://www.gradio.app/docs/gradio/barplot)
- [ ] [Button](https://www.gradio.app/docs/gradio/button)
- [ ] [Chatbot](https://www.gradio.app/docs/gradio/chatbot)
- [ ] [Checkbox](https://www.gradio.app/docs/gradio/checkbox)
- [ ] [CheckboxGroup](https://www.gradio.app/docs/gradio/checkboxgroup)
- [ ] [ClearButton](https://www.gradio.app/docs/gradio/clearbutton)
- [ ] [Code](https://www.gradio.app/docs/gradio/code)
- [ ] [ColorPicker](https://www.gradio.app/docs/gradio/colorpicker)
- [ ] [Dataframe](https://www.gradio.app/docs/gradio/dataframe)
- [ ] [Dataset](https://www.gradio.app/docs/gradio/dataset)
- [ ] [DateTime](https://www.gradio.app/docs/gradio/datetime)
- [ ] [DownloadButton](https://www.gradio.app/docs/gradio/downloadbutton)
- [ ] [Dropdown](https://www.gradio.app/docs/gradio/dropdown)
- [ ] [DuplicateButton](https://www.gradio.app/docs/gradio/duplicatebutton)
- [ ] [File](https://www.gradio.app/docs/gradio/file)
- [ ] [FileExplorer](https://www.gradio.app/docs/gradio/fileexplorer)
- [ ] [Gallery](https://www.gradio.app/docs/gradio/gallery)
- [ ] [HighlightedText](https://www.gradio.app/docs/gradio/highlightedtext)
- [ ] [HTML](https://www.gradio.app/docs/gradio/html)
- [ ] [Image](https://www.gradio.app/docs/gradio/image)
- [ ] [ImageEditor](https://www.gradio.app/docs/gradio/imageeditor)
- [ ] [JSON](https://www.gradio.app/docs/gradio/json)
- [ ] [Label](https://www.gradio.app/docs/gradio/label)
- [ ] [LinePlot](https://www.gradio.app/docs/gradio/lineplot)
- [ ] [LoginButton](https://www.gradio.app/docs/gradio/loginbutton)
- [ ] [LogoutButton](https://www.gradio.app/docs/gradio/logoutbutton)
- [ ] [Markdown](https://www.gradio.app/docs/gradio/markdown)
- [ ] [Model3D](https://www.gradio.app/docs/gradio/model3d)
- [ ] [MultimodalTextbox](https://www.gradio.app/docs/gradio/multimodaltextbox)
- [ ] [Number](https://www.gradio.app/docs/gradio/number)
- [ ] [ParamViewer](https://www.gradio.app/docs/gradio/paramviewer)
- [ ] [Plot](https://www.gradio.app/docs/gradio/plot)
- [ ] [Radio](https://www.gradio.app/docs/gradio/radio)
- [ ] [ScatterPlot](https://www.gradio.app/docs/gradio/scatterplot)
- [ ] [SimpleImage](https://www.gradio.app/docs/gradio/simpleimage)
- [ ] [Slider](https://www.gradio.app/docs/gradio/slider)
- [ ] [State](https://www.gradio.app/docs/gradio/state)
- [ ] [Textbox](https://www.gradio.app/docs/gradio/textbox)
- [ ] [Timer](https://www.gradio.app/docs/gradio/timer)
- [ ] [UploadButton](https://www.gradio.app/docs/gradio/uploadbutton)
- [ ] [Video](https://www.gradio.app/docs/gradio/video)
