### ISSUE TITLE
Remaining SSR todos

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#9417]
- [x] Update Spaces Dockerfile to include Node and run Gradio apps in SSR mode by default
- [x] Add e2e tests in SSR mode
- [ ] The `title` parameter of `ChatInterface` and `Interface` is not centered in SSR mode
- [x] Ensure custom components work
- [x] Ensure gradio dev mode works
- [x] Ensure that `auth` and other kwargs in `gr.mount_gradio_app` work with SSR (https://github.com/gradio-app/gradio/issues/10204)
- [x] Ensure that `head` and `css` parameters work with SSR
- [x] Ensure that `scale` is taken into account on the node server: e.g. notice how this loads https://huggingface.co/spaces/gradio-templates/text-to-image-gradio-template
- [x] Issue related to interaction between SSR and the iframe resizer ([see internal link](https://huggingface.slack.com/archives/C02SPHC1KD1/p1728604311450969))
- [x] Some elements (like tabs) take a long time to hydrate, see [this Space](https://huggingface.co/spaces/IAMJB/test-paper-central)
- [ ] Ensure google fonts work for themes

**Comment by franz101** [comment]
what am I missing here for sir to work?
https://colab.research.google.com/drive/1RlRZk1mcs6atrKwKErVrK0gqaTHSfTBl?usp=sharing

**Comment by abidlabs** [comment]
Going to close this as we have only a couple of issues left, which have dedicated issues
