### ISSUE TITLE
ZeroGPU integration tracking

### ISSUE THREAD

**Issue by cbensimon** [gradio-app/gradio#9824]
Simple issue to track potential improvements with ZeroGPU / Gradio integration

Currently, [`spaces.zero`](https://github.com/huggingface/pyspaces/tree/main/spaces/zero) package does various hacks to make Gradio work smoothly with ZeroGPU

Of course we don't want those hacks to be done the other way around (on Gradio side), it would be equally bad.
The idea is to see if we can possibly improve things such that the hacks are simply not needed anymore (win on both sides).

## Integration
- [ ] Make queue events multiprocessing compatible :
  - [spaces.zero.gradio:118](https://github.com/huggingface/pyspaces/blob/f50956cde0ce117635ed553a271e20e5e66e0bdf/spaces/zero/gradio.py#L118)
- [ ] Connection events (at least “disconnect” event) :
  - [spaces.zero.gradio:60](https://github.com/huggingface/pyspaces/blob/f50956cde0ce117635ed553a271e20e5e66e0bdf/spaces/zero/gradio.py#L60)
  - [spaces.zero.client:144](https://github.com/huggingface/pyspaces/blob/f50956cde0ce117635ed553a271e20e5e66e0bdf/spaces/zero/client.py#L144)
- [ ] Allow defining a global “on_launch” (should probably be stateful) :
  - [spaces.zero.gradio:138](https://github.com/huggingface/pyspaces/blob/f50956cde0ce117635ed553a271e20e5e66e0bdf/spaces/zero/gradio.py#L138)
  - [spaces.zero.\_\_init\_\_:20](https://github.com/huggingface/pyspaces/blob/f50956cde0ce117635ed553a271e20e5e66e0bdf/spaces/zero/__init__.py#L20)
- [ ] Enforce serialization (gr.Progress, etc.) :
  - [spaces.zero.gradio:120](https://github.com/huggingface/pyspaces/blob/f50956cde0ce117635ed553a271e20e5e66e0bdf/spaces/zero/gradio.py#L120)
  - [spaces.zero.gradio:32](https://github.com/huggingface/pyspaces/blob/f50956cde0ce117635ed553a271e20e5e66e0bdf/spaces/zero/gradio.py#L32)

## Potential improvements / feature requests
- [ ] `gr.Info(...); info.close(success: bool)`
- [x] Always get auth from postMessage API (requires HF-Hub handshake)
- [ ] Allow `raise gr.Error` to not affect output components (similar to `gr.Skip`)
- [x] Allow `raise gr.Erorr` to not print traceback
- [ ] Gracefully handle backend switches (404 session not found error). Not specific to ZeroGPU but switches are more frequent than classical Spaces

**Comment by abidlabs** [comment]
@cbensimon which of these are still open issues? Can you elaborate on the issues so we can work on them?

**Comment by abidlabs** [comment]
I think I understand this one:

> Allow raise gr.Error to not affect output components (similar to gr.Skip)

but the 6 other tracking issues are pretty abbreviated and not clear to me what they mean. For example, what's this?

> gr.Info(...); info.close(success: bool)

**Comment by freddyaboulton** [comment]
Hi @cbensimon ! We were playing with lots of Zero GPU spaces and want to get your thoughts on this idea:

Instead of using gr.Info to tell users the status of acquiring the GPU, use gr.Progress to display in the output component. I think this happens by default when the zero-gpu-annotated function has a gr.Progress but can it be done by default?
